# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#'
#' @param x A single integer
#' @export
timesTwo <- function(x) {
    .Call('_packdevel_timesTwo', PACKAGE = 'packdevel', x)
}

timesThree <- function(x) {
    .Call('_packdevel_timesThree', PACKAGE = 'packdevel', x)
}

wait_a_second_omp <- function(sec, ncores) {
    .Call('_packdevel_wait_a_second_omp', PACKAGE = 'packdevel', sec, ncores)
}

